- name: Install Fluent Bit package from URL
  ansible.builtin.apt:
    deb: "{{ fb_package_url }}"
    # We want our package to overwrite the one that comes with the Infra Agent, even if it implies downgrading it
    allow_downgrade: true
    state: present
  become: true