- name: Install Fluent Bit package
  community.general.zypper:
    name: "{{ fb_package_url }}"
    # We want our package to overwrite the one that comes with the Infra Agent, even if it implies downgrading it
    oldpackage: true
    state: present
  become: true